### ISSUE TITLE
레파지토리 이름이 잘못된것같습니다.

### ISSUE THREAD

**Issue by kimxwan0319** [oajh04/han_kakao#1]
`han_kakao` 를 `su_kakao`로 고쳐주세요.

**Comment by eungyeole** [comment]
동의합니다

**Comment by leeseojune53** [comment]
Critical한 Bug네요 빨리 해결해주세요!

**Comment by smoothbear** [comment]
Please rename this repository to su_kakao.

**Comment by shw0471** [comment]
이거 이대로 가면 큰 버그 생길것같네요ㅠ

**Comment by kimxwan0319** [comment]
@oajh04 이슈 해결없이 클로즈 된 이유가 알 수 있을까요?

**Comment by oajh04** [comment]
무슨 소린가요 이슈해결 했습니다만
